name: dataset # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: dataset tools for working with JSON objects as collections # 79 char long summary
description: |
        The Dataset Project provides tools for working with collections of 
        JSON Object documents stored on the local file system. Two tools
        are provided. The _dataset_ cli is for use interactively at the
        shell level and _datasetd_ is a web service that works as a JSON
        API.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  dataset:
        command: bin/dataset
        plugs:
                - home
  datasetd:
        command: bin/datasetd
        daemon: simple
        plugs:
                - home

parts:
  dataset:
    plugin: go
    go-channel: stable
    build-environment:
            - "CGO_ENABLED" : "0"
    source-type: git
    source: https://github.com/caltechlibrary/dataset
