name: dataset # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '2.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: dataset provides tools for working with JSON objects as collections
description: |
  The Dataset Project provides tools for working with collections of 
  JSON object documents. Two tools are provided. The _dataset_ cli is
  for use interactively at the shell level and _datasetd_ is a web
  service providing a JSON API.

grade: devmode # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  dataset:
    command: bin/dataset
    plugs:
      - home
      - desktop
      - removable-media
      - network
  datasetd:
    command: bin/datasetd
    daemon: simple
    plugs:
      - home
      - desktop
      - network
      - removable-media

parts:
  dataset:
    plugin: go
    go-channel: stable
    build-environment:
            - "CGO_ENABLED" : "1"
    source-type: git
    source: https://github.com/caltechlibrary/dataset
